#ifndef CSS_H_INCLUDED //les derectives de precompilation
#define CSS_H_INCLUDED
/**
 * css pour les objets graphiques
 */
static const char *css_reset="* {color: black;font-size: inherit;background-color: initial;font-family: inherit;font-style: inherit;font-variant: inherit;font-weight: inherit;text-shadow: inherit;icon-shadow: inherit;box-shadow: initial;margin-top: initial;margin-left: initial;margin-bottom: initial;margin-right: initial;padding-top: initial;padding-left: initial;padding-bottom: initial; padding-right: initial;border-top-style: initial;border-top-width: initial;border-left-style: initial;border-left-width: initial;border-bottom-style: initial;border-bottom-width: initial;border-right-style: initial;border-right-width: initial;border-top-left-radius: initial;border-top-right-radius: initial;border-bottom-right-radius: initial; border-bottom-left-radius: initial;outline-style: initial;outline-width: initial;outline-offset: initial;background-clip: initial;background-origin: initial;background-size: initial;background-position: initial;border-top-color: initial;border-right-color: initial;border-bottom-color: initial;border-left-color: initial;outline-color:  initial;background-repeat: initial;background-image: initial;border-image-source: initial;border-image-repeat: initial;border-image-slice: initial;border-image-width: initial;transition-property: initial;transition-duration: initial;transition-timing-function: initial;  transition-delay: initial;engine: initial; gtk-key-bindings: initial;  -GtkWidget-focus-line-width: 0;  -GtkWidget-focus-padding: 0;  -GtkNotebook-initial-gap: 0;} *{transition-property: color, background-color, border-color, background-image, padding, border-width;transition-duration: 1s;font: 'roboto light' 12px;}";
static const char *connexion_css="GtkWindow {background-color: #fff}"
                                 "GtkNotebook tab{background-color:#0F1827;padding:4px;}"
                                 ".labelWhite{color:#fff;} "
                                 "GtkNotebook tab:active{background-color:#4ebdf1;padding:5px;}"
                                 "GtkNotebook{background-color:#1CA9F0;}"
                                 ".button {color: black;background-color: #FFFFFF;border-style: solid;border-width:1px;border-color: #333;padding:2px;}"
                                 ".button:first-child {border-radius:10px;}"
                                 ".button:last-child {border-radius:10px;border-width:1px;}"
                                 ".button:hover {background-color: #cbcbcb;}"
                                 ".button *:hover {color: white;}"
                                 ".button:hover:active,.button:active {background-color: #993401;}"
                                 "GtkEntry{background-color:white;color:#bebebe;border-style: solid;border-width:1px;border-color: #333;padding:2px;color:black;font: 'roboto light' 10px;}"
                                 "GtkEntry:focus{border-style: dashed;border-width:2px;border-color:#64a6f7;}"
                                 ".button.newPlayerbtn{background-color:#1CA9F0;border:none;} ";
static const char *paneladmin_css=".adminpanelwin {background-color: #646464;background-image:url('bg.png');}"
                                  ".button{} .newPartie{background-image:url('AJ-p.png');background-size:100%;background-position:0px 0px;}"
                                  ".newPartie:hover{background-image:url('AJ-p-h.png');background-size:100%;background-position:0px 0px;}"
                                  ".editpartieButton{background-image:url('MD-p.png');background-size:100%;background-position:0px 0px;}"
                                  ".editpartieButton:hover{background-image:url('MD-p-h.png');background-size:100%;background-position:0px 0px;}"
                                  ".deletepartieButton{background-image:url('SP-p.png');background-size:100%;background-position:0px 0px;}"
                                  ".deletepartieButton:hover{background-image:url('SP-p-h.png');background-size:100%;background-position:0px 0px;}"
                                  ".logoutAdminButton{background-image:url('DC.png');background-size:100%;background-position:0px 0px;padding:6px;}"
                                  ".logoutAdminButton:hover{background-image:url('DC-h.png');background-size:100%;background-position:0px 0px;padding:6px;}"
                                  "GtkScrolledWindow GtkGrid { background-color: #000; }"
                                  "GtkScrolledWindow .right,.left,.top,.bottom{background-color: darkGreen;color: black;-GtkScrollbar-has-backward-stepper: false;-GtkScrollbar-has-forward-stepper: false; -GtkRange-trough-border: 0;}"
                                  "GtkTreeView{ }"
                                  "GtkTreeView .button GtkLabel, .nbrPartie,.nbrPlayer{color:#fff;font-weight: bold; }"
                                  "GtkTreeView .button{background-color:#872626;padding:10px;color:#fff;}"
                                  "GtkTreeView row:nth-child(odd) { background-color: #e6e6e6; }"
                                  "GtkTreeView row:nth-child(even) { background-color: #a6cda7; }"
                                  "GtkTreeView row:hover{padding:15px 0px 15px 0px;background-color:#ccc;}";
static const char *newPartie_css=".NewPartieWindow{background-color: #646464;background-image:url('matrice_ad.png');} "
                                ".validate{background-image:url('valider.png');background-size:100%;background-position:0px 0px;}"
                                ".validate:hover{background-image:url('valider-h.png');background-size:100%;background-position:0px 0px;}"
                                ".shuffle{background-image:url('melanger.png');background-size:100%;background-position:0px 0px;}"
                                ".shuffle:hover{background-image:url('melanger-h.png');background-size:100%;background-position:0px 0px;}"
                                ".cancel{background-image:url('annuler.png');background-size:100%;background-position:0px 0px;}"
                                ".cancel:hover{background-image:url('annuler-h.png');background-size:100%;background-position:0px 0px;}"
                                ".mygrid .buttonFace{background-color:#cf5;border-radius:6px;font: Comic Sans 80;font-weight: bold;}"
                                ".mygrid .button GtkLabel{color:#000;font-weight: bold;font: Comic Sans 35;}";
static const char *playerPanel_css=".playerPanelWin{background-color: #646464;background-image:url('playerPanel.png');}"
                                   ".logoutAdminButton{background-image:url('DC.png');background-size:100%;background-position:0px 0px;padding:6px;}"
                                   ".logoutAdminButton:hover{background-image:url('DC-h.png');background-size:100%;background-position:0px 0px;padding:6px;}"
                                   "GtkScrolledWindow GtkGrid { background-color: #000; }"
                                   "GtkScrolledWindow .right,.left,.top,.bottom{background-color: darkGreen;color: black;-GtkScrollbar-has-backward-stepper: false;-GtkScrollbar-has-forward-stepper: false; -GtkRange-trough-border: 0;}"
                                   "GtkTreeView{ }"
                                   "GtkTreeView .button GtkLabel, .nbrPartie,.nbrPlayer{color:#fff;font-weight: bold; }"
                                   "GtkTreeView .button{background-color:#872626;padding:10px;color:#fff;}"
                                   "GtkTreeView row:nth-child(odd) { background-color: #e6e6e6; }"
                                   "GtkTreeView row:nth-child(even) { background-color: #a6cda7; }"
                                   "GtkTreeView row:hover{padding:15px 0px 15px 0px;background-color:#ccc;height:15px;}"
                                   ".play{background-image:url('play.png');background-size:100%;background-position:0px 0px;}"
                                   ".play:hover{background-image:url('play-h.png');background-size:100%;background-position:0px 0px;}"
                                   ".chalange{background-image:url('chalange.png');background-size:100%;background-position:0px 0px;}"
                                   ".chalange:hover{background-image:url('chalange-h.png');background-size:100%;background-position:0px 0px;}"
                                   ;
static const char *playGrid_css=".playGridWin{background-color: #646464;background-image:url('playGrid.png');}"
                                   "GtkScrolledWindow GtkGrid { background-color: #000; }"
                                   "GtkScrolledWindow .right,.left,.top,.bottom{background-color: darkGreen;color: black;-GtkScrollbar-has-backward-stepper: false;-GtkScrollbar-has-forward-stepper: false; -GtkRange-trough-border: 0;}"
                                   "GtkTreeView{ color:#fff;font-weight: bold;}"
                                   "GtkTreeView .button GtkLabel, .nbrPartie,.nbrPlayer{color:#fff;font-weight: bold; }"
                                   "GtkTreeView .button{background-color:#872626;padding:10px;color:#fff;}"
                                   "GtkTreeView row:nth-child(odd) { background-color: #e6e6e6; }"
                                   "GtkTreeView row:nth-child(even) { background-color: #a6cda7; }"
                                   "GtkTreeView row:hover{padding:15px 0px 15px 0px;background-color:#ccc;}"
                                   ".mygrid .buttonFace{background-color:#cf5;border-radius:6px;font: Comic Sans 80;font-weight: bold;}"
                                   ".mygrid .button GtkLabel{color:#000;font-weight: bold;font: Comic Sans 35;}"
                                   ".entry_word{color:#000;font-weight: bold;font: Comic Sans 19;} "
                                   ".mygrid .buttonSelected{background-color:#cf5;border-style: solid;border-width:3px;border-color: #00FF00;border-radius:6px;font: Comic Sans 80;font-weight: bold;}"
                                   ".mygrid .buttonNeighbor{background-color:#fff;border-radius:6px;font: Comic Sans 80;font-weight: bold;}"
                                   ".mygrid .buttonOldSelected{background-color:#cf5;border-radius:6px;font: Comic Sans 80;font-weight: bold;}"
                                   ;
#endif // CSS_H_INCLUDED
